// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analytics-a/BriefingA.tsx": () => import("../components/mockups/analytics-a/BriefingA.tsx"),
  "./components/mockups/analytics-b/CommandB.tsx": () => import("../components/mockups/analytics-b/CommandB.tsx"),
  "./components/mockups/analytics-c/MatrixC.tsx": () => import("../components/mockups/analytics-c/MatrixC.tsx"),
  "./components/mockups/analytics-d/InsightD.tsx": () => import("../components/mockups/analytics-d/InsightD.tsx")
};
