import { db, taiwanBrandsTable } from "@workspace/db";

const brands = [
  { name: "台積電", nameEn: "TSMC", ticker: "2330", industry: "semi", score: 85, weekChange: 3, status: "rising", description: "全球最大晶圓代工廠，為蘋果、輝達等科技巨頭製造晶片", website: "https://tsmc.com", employees: "73,000+", marketCap: "NT$18兆", knowledgeGraph: 91, aiCitation: 88, semanticSearch: 79, multimodal: 72 },
  { name: "聯發科", nameEn: "MediaTek", ticker: "2454", industry: "semi", score: 75, weekChange: 2, status: "rising", description: "全球前五大晶片設計公司，深耕智慧型手機與AIoT晶片", website: "https://mediatek.com", employees: "20,000+", marketCap: "NT$2.1兆", knowledgeGraph: 80, aiCitation: 76, semanticSearch: 70, multimodal: 62 },
  { name: "聯電", nameEn: "UMC", ticker: "2303", industry: "semi", score: 58, weekChange: 0, status: "stable", description: "台灣第二大晶圓代工廠，專注28nm及以上成熟製程", website: "https://umc.com", employees: "19,000+", marketCap: "NT$0.7兆", knowledgeGraph: 61, aiCitation: 58, semanticSearch: 55, multimodal: 49 },
  { name: "瑞昱半導體", nameEn: "Realtek", ticker: "2379", industry: "semi", score: 41, weekChange: 2, status: "rising", description: "全球領先的網路晶片、音效晶片IC設計公司", website: "https://realtek.com", employees: "5,800+", marketCap: "NT$0.35兆", knowledgeGraph: 44, aiCitation: 42, semanticSearch: 38, multimodal: 33 },
  { name: "南亞科技", nameEn: "Nanya Tech", ticker: "2408", industry: "semi", score: 33, weekChange: -1, status: "falling", description: "台灣主要DRAM記憶體製造商，台塑集團旗下", website: "https://nanya.com", employees: "6,200+", marketCap: "NT$0.28兆", knowledgeGraph: 36, aiCitation: 33, semanticSearch: 30, multimodal: 24 },
  { name: "鴻海精密", nameEn: "Foxconn", ticker: "2317", industry: "tech", score: 68, weekChange: -1, status: "falling", description: "全球最大電子代工廠，蘋果iPhone主要製造商", website: "https://foxconn.com", employees: "800,000+", marketCap: "NT$1.5兆", knowledgeGraph: 73, aiCitation: 70, semanticSearch: 62, multimodal: 55 },
  { name: "廣達電腦", nameEn: "Quanta Computer", ticker: "2382", industry: "tech", score: 53, weekChange: 4, status: "rising", description: "全球最大筆記型電腦ODM廠，積極布局AI伺服器", website: "https://quantatw.com", employees: "90,000+", marketCap: "NT$0.9兆", knowledgeGraph: 57, aiCitation: 55, semanticSearch: 50, multimodal: 43 },
  { name: "研華科技", nameEn: "Advantech", ticker: "2395", industry: "tech", score: 60, weekChange: 1, status: "rising", description: "工業電腦與IoT解決方案全球領導品牌", website: "https://advantech.com", employees: "9,500+", marketCap: "NT$0.4兆", knowledgeGraph: 65, aiCitation: 62, semanticSearch: 55, multimodal: 47 },
  { name: "微星科技", nameEn: "MSI", ticker: "2377", industry: "tech", score: 46, weekChange: -2, status: "falling", description: "全球知名電競電腦品牌，主機板、顯示卡、筆電", website: "https://msi.com", employees: "10,000+", marketCap: "NT$0.22兆", knowledgeGraph: 49, aiCitation: 47, semanticSearch: 43, multimodal: 37 },
  { name: "台達電子", nameEn: "Delta Electronics", ticker: "2308", industry: "tech", score: 72, weekChange: 3, status: "rising", description: "全球電源管理與散熱解決方案領導品牌，ESG標竿企業", website: "https://deltaww.com", employees: "90,000+", marketCap: "NT$0.85兆", knowledgeGraph: 77, aiCitation: 74, semanticSearch: 67, multimodal: 58 },
  { name: "富邦金控", nameEn: "Fubon Financial", ticker: "2881", industry: "finance", score: 64, weekChange: 5, status: "rising", description: "台灣最大金融控股集團，旗下富邦人壽、富邦銀行等", website: "https://fubon.com", employees: "40,000+", marketCap: "NT$1.2兆", knowledgeGraph: 68, aiCitation: 66, semanticSearch: 60, multimodal: 52 },
  { name: "國泰金控", nameEn: "Cathay Financial", ticker: "2882", industry: "finance", score: 62, weekChange: 1, status: "rising", description: "台灣資產規模最大的金融控股公司，旗下國泰人壽", website: "https://cathayholdings.com", employees: "45,000+", marketCap: "NT$1.1兆", knowledgeGraph: 66, aiCitation: 64, semanticSearch: 58, multimodal: 50 },
  { name: "中信金控", nameEn: "CTBC Financial", ticker: "2891", industry: "finance", score: 57, weekChange: -1, status: "falling", description: "中國信託金融控股，在亞洲擁有廣泛的分行網路", website: "https://ctbcholding.com", employees: "28,000+", marketCap: "NT$0.85兆", knowledgeGraph: 61, aiCitation: 58, semanticSearch: 53, multimodal: 45 },
  { name: "玉山金控", nameEn: "E.SUN Financial", ticker: "2884", industry: "finance", score: 55, weekChange: 2, status: "rising", description: "以數位金融創新著稱，獲得全球數位銀行獎項認可", website: "https://esunfhc.com", employees: "15,000+", marketCap: "NT$0.6兆", knowledgeGraph: 59, aiCitation: 56, semanticSearch: 52, multimodal: 44 },
  { name: "兆豐金控", nameEn: "Mega Financial", ticker: "2886", industry: "finance", score: 38, weekChange: 0, status: "stable", description: "國營金融控股集團，外貿融資業務強大", website: "https://megaholdings.com.tw", employees: "12,000+", marketCap: "NT$0.6兆", knowledgeGraph: 41, aiCitation: 38, semanticSearch: 35, multimodal: 29 },
  { name: "永豐金控", nameEn: "SinoPac Financial", ticker: "2890", industry: "finance", score: 31, weekChange: 1, status: "rising", description: "永豐金融控股，提供多元金融服務", website: "https://sinopacgroup.com", employees: "10,000+", marketCap: "NT$0.38兆", knowledgeGraph: 33, aiCitation: 31, semanticSearch: 28, multimodal: 24 },
  { name: "中華電信", nameEn: "Chunghwa Telecom", ticker: "2412", industry: "telecom", score: 71, weekChange: 2, status: "rising", description: "台灣最大電信業者，4G/5G、寬頻、企業雲端服務領導品牌", website: "https://cht.com.tw", employees: "22,000+", marketCap: "NT$0.8兆", knowledgeGraph: 76, aiCitation: 73, semanticSearch: 66, multimodal: 57 },
  { name: "台灣大哥大", nameEn: "Taiwan Mobile", ticker: "3045", industry: "telecom", score: 56, weekChange: 1, status: "rising", description: "台灣第二大電信業者，積極發展5G與數位服務", website: "https://taiwanmobile.com", employees: "6,000+", marketCap: "NT$0.35兆", knowledgeGraph: 60, aiCitation: 57, semanticSearch: 52, multimodal: 44 },
  { name: "遠傳電信", nameEn: "FarEasTone", ticker: "4904", industry: "telecom", score: 50, weekChange: -1, status: "falling", description: "遠東集團旗下電信業者，5G基礎建設積極擴展中", website: "https://fareastone.com.tw", employees: "5,500+", marketCap: "NT$0.3兆", knowledgeGraph: 54, aiCitation: 51, semanticSearch: 46, multimodal: 39 },
  { name: "亞太電信", nameEn: "Asia Pacific Telecom", ticker: "3682", industry: "telecom", score: 29, weekChange: -2, status: "falling", description: "台灣第四大電信商，已完成5G頻譜取得", website: "https://aptg.com.tw", employees: "2,000+", marketCap: "NT$0.08兆", knowledgeGraph: 31, aiCitation: 29, semanticSearch: 26, multimodal: 22 },
  { name: "統一超商", nameEn: "7-Eleven Taiwan", ticker: "2912", industry: "consumer", score: 74, weekChange: 4, status: "rising", description: "台灣最大便利商店連鎖，6,500+門市，品牌數位化領先", website: "https://7-eleven.com.tw", employees: "14,000+", marketCap: "NT$0.65兆", knowledgeGraph: 79, aiCitation: 76, semanticSearch: 70, multimodal: 62 },
  { name: "統一企業", nameEn: "Uni-President", ticker: "1216", industry: "consumer", score: 49, weekChange: 1, status: "rising", description: "台灣食品飲料龍頭，旗下統一超商、星巴克台灣等", website: "https://uni-president.com.tw", employees: "30,000+", marketCap: "NT$0.45兆", knowledgeGraph: 52, aiCitation: 50, semanticSearch: 46, multimodal: 39 },
  { name: "全家便利商店", nameEn: "FamilyMart Taiwan", ticker: "5903", industry: "consumer", score: 44, weekChange: 0, status: "stable", description: "台灣第二大便利商店連鎖，積極推進數位支付與App服務", website: "https://family.com.tw", employees: "6,500+", marketCap: "NT$0.18兆", knowledgeGraph: 47, aiCitation: 45, semanticSearch: 41, multimodal: 35 },
  { name: "寶雅國際", nameEn: "Poya International", ticker: "5904", industry: "consumer", score: 41, weekChange: 2, status: "rising", description: "台灣最大美妝生活雜貨連鎖，快速拓展全台門市", website: "https://poya.com.tw", employees: "5,000+", marketCap: "NT$0.2兆", knowledgeGraph: 44, aiCitation: 42, semanticSearch: 38, multimodal: 32 },
  { name: "大潤發流通", nameEn: "RT-Mart", ticker: "2945", industry: "consumer", score: 30, weekChange: -1, status: "falling", description: "台灣大型量販店連鎖，已被全聯收購整合中", website: "https://rt-mart.com.tw", employees: "8,000+", marketCap: "NT$0.1兆", knowledgeGraph: 32, aiCitation: 30, semanticSearch: 27, multimodal: 23 },
  { name: "台灣水泥", nameEn: "Taiwan Cement", ticker: "1101", industry: "esg", score: 36, weekChange: 0, status: "stable", description: "台灣最大水泥製造商，積極轉型儲能與綠能事業", website: "https://twcement.com.tw", employees: "8,000+", marketCap: "NT$0.3兆", knowledgeGraph: 39, aiCitation: 36, semanticSearch: 33, multimodal: 27 },
  { name: "中國鋼鐵", nameEn: "China Steel", ticker: "2002", industry: "esg", score: 39, weekChange: -1, status: "falling", description: "台灣最大鋼鐵製造商，積極推進低碳鋼鐵技術", website: "https://csc.com.tw", employees: "9,500+", marketCap: "NT$0.4兆", knowledgeGraph: 42, aiCitation: 39, semanticSearch: 36, multimodal: 30 },
  { name: "台塑集團", nameEn: "Formosa Plastics", ticker: "1301", industry: "esg", score: 43, weekChange: 1, status: "rising", description: "台灣最大石化集團，積極投入碳捕捉與循環經濟", website: "https://fpg.com.tw", employees: "100,000+", marketCap: "NT$0.7兆", knowledgeGraph: 46, aiCitation: 44, semanticSearch: 40, multimodal: 34 },
  { name: "日月光半導體", nameEn: "ASE Technology", ticker: "3711", industry: "semi", score: 48, weekChange: 1, status: "rising", description: "全球最大半導體封裝測試廠，強化先進封裝布局", website: "https://aseglobal.com", employees: "90,000+", marketCap: "NT$0.65兆", knowledgeGraph: 52, aiCitation: 49, semanticSearch: 44, multimodal: 37 },
  { name: "台灣菸酒", nameEn: "TTL", ticker: "1301", industry: "consumer", score: 35, weekChange: 0, status: "stable", description: "國營企業，台灣啤酒及高粱酒市場領導品牌", website: "https://ttl.com.tw", employees: "6,000+", marketCap: "NT$國營", knowledgeGraph: 38, aiCitation: 35, semanticSearch: 32, multimodal: 26 },
];

async function seedTaiwanBrands() {
  console.log("🌱 Seeding Taiwan brands...");
  const existing = await db.select().from(taiwanBrandsTable);
  if (existing.length > 0) {
    console.log(`✅ ${existing.length} brands already seeded. Skipping.`);
    return;
  }
  await db.insert(taiwanBrandsTable).values(brands);
  console.log(`✅ Seeded ${brands.length} Taiwan brands.`);
}

seedTaiwanBrands()
  .then(() => process.exit(0))
  .catch((e) => { console.error(e); process.exit(1); });
